/**
 * Command Metadata Part 4 - Browser and MIDI Controls commands
 *
 * AIDEV-NOTE: This file continues the command metadata.
 * It contains Browser (List, Tree, Favorites) and Global MIDI Controls
 * (Buttons, Knobs, Faders) commands.
 *
 * @see cmdr/cmdr.TsiLib/Commands/Interpretation/KnownCommands.cs
 */

import { Categories } from "./categories";
import type { CommandDescriptionInput } from "./command-description";
import { CommandInType, CommandOutType, FloatRangeType } from "./command-types";
import { KnownCommands } from "./known-commands";
import { TargetType } from "./target-type";

/**
 * Browser and MIDI Controls command metadata.
 */
export const COMMAND_METADATA_PART4: Record<number, CommandDescriptionInput> = {
  // ===========================================================================
  // BROWSER - LIST
  // ===========================================================================
  [KnownCommands.Browser_List_Delete]: {
    name: "Delete (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_ResetPlayedState]: {
    name: "Reset Played State (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_Analyze]: {
    name: "Analyze (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_AnalysisLock]: {
    name: "Analysis Lock (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_AnalysisUnlock]: {
    name: "Analysis Unlock (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_Edit]: {
    name: "Edit (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_Relocate]: {
    name: "Relocate (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_AddAsTrackToCollection]: {
    name: "Add As Track To Collection",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_AddAsOneShotSampleToCollection]: {
    name: "Add As One-Shot Sample To Collection",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_AddAsLoopToCollection]: {
    name: "Add As Loop To Collection",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_SetToOneShotSample]: {
    name: "Set To One-Shot Sample",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_SetToLoopedSample]: {
    name: "Set To Looped Sample",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_SetToTrack]: {
    name: "Set To Track",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_SelectUpDown]: {
    name: "Select Up/Down (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "UpDown",
  },
  [KnownCommands.Browser_List_SelectPageUpDown]: {
    name: "Select Page Up/Down (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "UpDown",
  },
  [KnownCommands.Browser_List_SelectTopBottom]: {
    name: "Select Top/Bottom (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "UpDown",
  },
  [KnownCommands.Browser_List_SelectExtendUpDown]: {
    name: "Select Extend Up/Down (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "UpDown",
  },
  [KnownCommands.Browser_List_SelectExtendPageUpDown]: {
    name: "Select Extend Page Up/Down (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "UpDown",
  },
  [KnownCommands.Browser_List_SelectExtendTopBottom]: {
    name: "Select Extend Top/Bottom (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "UpDown",
  },
  [KnownCommands.Browser_List_SelectAll]: {
    name: "Select All (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_Consolidate]: {
    name: "Consolidate (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_Search]: {
    name: "Search (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_SearchClear]: {
    name: "Search Clear (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_SearchInPlaylists]: {
    name: "Search In Playlists",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_ShowInExplorer]: {
    name: "Show In Explorer",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_Clear]: {
    name: "Clear (Browser List)",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_ExpandRemixSet]: {
    name: "Expand Remix Set",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_JumpToCurrentTrack]: {
    name: "Jump To Current Track",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_AppendToPreparationList]: {
    name: "Append To Preparation List",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_AddOrRemoveTrackfromPreparationList]: {
    name: "Add/Remove Track from Preparation List",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_AddAsNextToPreparationList]: {
    name: "Add As Next To Preparation List",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_List_ExportAsRemixSet]: {
    name: "Export As Remix Set",
    category: Categories.Browser_List,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // BROWSER - TREE
  // ===========================================================================
  [KnownCommands.Browser_Tree_AnalysisLock]: {
    name: "Analysis Lock (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_AnalysisUnlock]: {
    name: "Analysis Unlock (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_SaveCollection]: {
    name: "Save Collection",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_Delete]: {
    name: "Delete (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_ResetPlayedState]: {
    name: "Reset Played State (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_Analyze]: {
    name: "Analyze (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_RestoreAutoGain]: {
    name: "Restore Auto-Gain",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_Edit]: {
    name: "Edit (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_Relocate]: {
    name: "Relocate (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_ImportCollection]: {
    name: "Import Collection",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_ImportMusicFolders]: {
    name: "Import Music Folders",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_Export]: {
    name: "Export (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_ExportPrintable]: {
    name: "Export Printable",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_RenamePlaylistOrFolder]: {
    name: "Rename Playlist Or Folder",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_SelectUpDown]: {
    name: "Select Up/Down (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "UpDown",
  },
  [KnownCommands.Browser_Tree_SelectExpandCollapse]: {
    name: "Select Expand/Collapse (Browser Tree)",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ExpandCollapse",
  },
  [KnownCommands.Browser_Tree_CreatePlaylist]: {
    name: "Create Playlist",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_DeletePlaylist]: {
    name: "Delete Playlist",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_CreatePlaylistFolder]: {
    name: "Create Playlist Folder",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_DeletePlaylistFolder]: {
    name: "Delete Playlist Folder",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_RefreshExplorerFolderContent]: {
    name: "Refresh Explorer Folder Content",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_CheckConsistency]: {
    name: "Check Consistency",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Browser_Tree_AddFolderToMusicFolders]: {
    name: "Add Folder To Music Folders",
    category: Categories.Browser_Tree,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // BROWSER - FAVORITES
  // ===========================================================================
  [KnownCommands.Browser_Favorites_Selector]: {
    name: "Favorites Selector",
    category: Categories.Browser_Favorites,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "Favorites",
  },
  [KnownCommands.Browser_Favorites_AddFolderToFavorites]: {
    name: "Add Folder To Favorites",
    category: Categories.Browser_Favorites,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // GLOBAL - MIDI CONTROLS - BUTTONS
  // ===========================================================================
  [KnownCommands.Global_MidiControls_Buttons_MidiButton1]: {
    name: "MIDI Button 1",
    category: Categories.Global_MidiControls_Buttons,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_MidiControls_Buttons_MidiButton2]: {
    name: "MIDI Button 2",
    category: Categories.Global_MidiControls_Buttons,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_MidiControls_Buttons_MidiButton3]: {
    name: "MIDI Button 3",
    category: Categories.Global_MidiControls_Buttons,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_MidiControls_Buttons_MidiButton4]: {
    name: "MIDI Button 4",
    category: Categories.Global_MidiControls_Buttons,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_MidiControls_Buttons_MidiButton5]: {
    name: "MIDI Button 5",
    category: Categories.Global_MidiControls_Buttons,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_MidiControls_Buttons_MidiButton6]: {
    name: "MIDI Button 6",
    category: Categories.Global_MidiControls_Buttons,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_MidiControls_Buttons_MidiButton7]: {
    name: "MIDI Button 7",
    category: Categories.Global_MidiControls_Buttons,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_MidiControls_Buttons_MidiButton8]: {
    name: "MIDI Button 8",
    category: Categories.Global_MidiControls_Buttons,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },

  // ===========================================================================
  // GLOBAL - MIDI CONTROLS - KNOBS
  // ===========================================================================
  [KnownCommands.Global_MidiControls_Knobs_MidiKnob1]: {
    name: "MIDI Knob 1",
    category: Categories.Global_MidiControls_Knobs,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiKnob2]: {
    name: "MIDI Knob 2",
    category: Categories.Global_MidiControls_Knobs,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiKnob3]: {
    name: "MIDI Knob 3",
    category: Categories.Global_MidiControls_Knobs,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiKnob4]: {
    name: "MIDI Knob 4",
    category: Categories.Global_MidiControls_Knobs,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiKnob5]: {
    name: "MIDI Knob 5",
    category: Categories.Global_MidiControls_Knobs,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiKnob6]: {
    name: "MIDI Knob 6",
    category: Categories.Global_MidiControls_Knobs,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiKnob7]: {
    name: "MIDI Knob 7",
    category: Categories.Global_MidiControls_Knobs,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiKnob8]: {
    name: "MIDI Knob 8",
    category: Categories.Global_MidiControls_Knobs,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },

  // ===========================================================================
  // GLOBAL - MIDI CONTROLS - FADERS
  // ===========================================================================
  [KnownCommands.Global_MidiControls_Knobs_MidiFader1]: {
    name: "MIDI Fader 1",
    category: Categories.Global_MidiControls_Faders,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiFader2]: {
    name: "MIDI Fader 2",
    category: Categories.Global_MidiControls_Faders,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiFader3]: {
    name: "MIDI Fader 3",
    category: Categories.Global_MidiControls_Faders,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiFader4]: {
    name: "MIDI Fader 4",
    category: Categories.Global_MidiControls_Faders,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiFader5]: {
    name: "MIDI Fader 5",
    category: Categories.Global_MidiControls_Faders,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiFader6]: {
    name: "MIDI Fader 6",
    category: Categories.Global_MidiControls_Faders,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiFader7]: {
    name: "MIDI Fader 7",
    category: Categories.Global_MidiControls_Faders,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Global_MidiControls_Knobs_MidiFader8]: {
    name: "MIDI Fader 8",
    category: Categories.Global_MidiControls_Faders,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
};
