/**
 * Command Metadata - Remix Deck Direct Mapping Slots
 *
 * AIDEV-NOTE: This file contains the Remix Deck Direct Mapping Slot commands.
 * These are the Cell Trigger and Cell State commands for Slots 1-4,
 * with 16 cells each (64 triggers + 64 states = 128 commands total).
 *
 * Cell triggers: Hold input / Trigger output
 * Cell states: None input / Enum output (SlotCellState)
 *
 * @see cmdr/cmdr.TsiLib/Commands/Interpretation/KnownCommands.cs
 */

import { Categories } from "./categories";
import type { CommandDescriptionInput } from "./command-description";
import { CommandInType, CommandOutType } from "./command-types";
import { KnownCommands } from "./known-commands";
import { TargetType } from "./target-type";

/**
 * Remix Deck Direct Mapping Slot command metadata.
 * Slots 1-4, each with 16 cell triggers and 16 cell states.
 */
export const COMMAND_METADATA_SLOTS: Record<number, CommandDescriptionInput> = {
  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING - SLOT 1 CELL TRIGGERS
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell1Trigger]: {
    name: "Slot 1 Cell 1 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell2Trigger]: {
    name: "Slot 1 Cell 2 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell3Trigger]: {
    name: "Slot 1 Cell 3 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell4Trigger]: {
    name: "Slot 1 Cell 4 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell5Trigger]: {
    name: "Slot 1 Cell 5 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell6Trigger]: {
    name: "Slot 1 Cell 6 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell7Trigger]: {
    name: "Slot 1 Cell 7 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell8Trigger]: {
    name: "Slot 1 Cell 8 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell9Trigger]: {
    name: "Slot 1 Cell 9 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell10Trigger]: {
    name: "Slot 1 Cell 10 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell11Trigger]: {
    name: "Slot 1 Cell 11 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell12Trigger]: {
    name: "Slot 1 Cell 12 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell13Trigger]: {
    name: "Slot 1 Cell 13 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell14Trigger]: {
    name: "Slot 1 Cell 14 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell15Trigger]: {
    name: "Slot 1 Cell 15 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell16Trigger]: {
    name: "Slot 1 Cell 16 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING - SLOT 1 CELL STATES
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell1State]: {
    name: "Slot 1 Cell 1 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell2State]: {
    name: "Slot 1 Cell 2 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell3State]: {
    name: "Slot 1 Cell 3 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell4State]: {
    name: "Slot 1 Cell 4 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell5State]: {
    name: "Slot 1 Cell 5 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell6State]: {
    name: "Slot 1 Cell 6 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell7State]: {
    name: "Slot 1 Cell 7 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell8State]: {
    name: "Slot 1 Cell 8 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell9State]: {
    name: "Slot 1 Cell 9 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell10State]: {
    name: "Slot 1 Cell 10 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell11State]: {
    name: "Slot 1 Cell 11 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell12State]: {
    name: "Slot 1 Cell 12 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell13State]: {
    name: "Slot 1 Cell 13 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell14State]: {
    name: "Slot 1 Cell 14 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell15State]: {
    name: "Slot 1 Cell 15 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot1_Slot1Cell16State]: {
    name: "Slot 1 Cell 16 State",
    category: Categories.RemixDeck_DirectMapping_Slot1,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },

  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING - SLOT 2 CELL TRIGGERS
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell1Trigger]: {
    name: "Slot 2 Cell 1 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell2Trigger]: {
    name: "Slot 2 Cell 2 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell3Trigger]: {
    name: "Slot 2 Cell 3 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell4Trigger]: {
    name: "Slot 2 Cell 4 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell5Trigger]: {
    name: "Slot 2 Cell 5 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell6Trigger]: {
    name: "Slot 2 Cell 6 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell7Trigger]: {
    name: "Slot 2 Cell 7 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell8Trigger]: {
    name: "Slot 2 Cell 8 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell9Trigger]: {
    name: "Slot 2 Cell 9 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell10Trigger]: {
    name: "Slot 2 Cell 10 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell11Trigger]: {
    name: "Slot 2 Cell 11 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell12Trigger]: {
    name: "Slot 2 Cell 12 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell13Trigger]: {
    name: "Slot 2 Cell 13 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell14Trigger]: {
    name: "Slot 2 Cell 14 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell15Trigger]: {
    name: "Slot 2 Cell 15 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell16Trigger]: {
    name: "Slot 2 Cell 16 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING - SLOT 2 CELL STATES
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell1State]: {
    name: "Slot 2 Cell 1 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell2State]: {
    name: "Slot 2 Cell 2 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell3State]: {
    name: "Slot 2 Cell 3 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell4State]: {
    name: "Slot 2 Cell 4 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell5State]: {
    name: "Slot 2 Cell 5 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell6State]: {
    name: "Slot 2 Cell 6 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell7State]: {
    name: "Slot 2 Cell 7 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell8State]: {
    name: "Slot 2 Cell 8 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell9State]: {
    name: "Slot 2 Cell 9 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell10State]: {
    name: "Slot 2 Cell 10 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell11State]: {
    name: "Slot 2 Cell 11 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell12State]: {
    name: "Slot 2 Cell 12 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell13State]: {
    name: "Slot 2 Cell 13 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell14State]: {
    name: "Slot 2 Cell 14 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell15State]: {
    name: "Slot 2 Cell 15 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot2_Slot2Cell16State]: {
    name: "Slot 2 Cell 16 State",
    category: Categories.RemixDeck_DirectMapping_Slot2,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },

  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING - SLOT 3 CELL TRIGGERS
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell1Trigger]: {
    name: "Slot 3 Cell 1 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell2Trigger]: {
    name: "Slot 3 Cell 2 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell3Trigger]: {
    name: "Slot 3 Cell 3 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell4Trigger]: {
    name: "Slot 3 Cell 4 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell5Trigger]: {
    name: "Slot 3 Cell 5 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell6Trigger]: {
    name: "Slot 3 Cell 6 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell7Trigger]: {
    name: "Slot 3 Cell 7 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell8Trigger]: {
    name: "Slot 3 Cell 8 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell9Trigger]: {
    name: "Slot 3 Cell 9 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell10Trigger]: {
    name: "Slot 3 Cell 10 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell11Trigger]: {
    name: "Slot 3 Cell 11 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell12Trigger]: {
    name: "Slot 3 Cell 12 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell13Trigger]: {
    name: "Slot 3 Cell 13 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell14Trigger]: {
    name: "Slot 3 Cell 14 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell15Trigger]: {
    name: "Slot 3 Cell 15 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell16Trigger]: {
    name: "Slot 3 Cell 16 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING - SLOT 3 CELL STATES
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell1State]: {
    name: "Slot 3 Cell 1 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell2State]: {
    name: "Slot 3 Cell 2 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell3State]: {
    name: "Slot 3 Cell 3 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell4State]: {
    name: "Slot 3 Cell 4 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell5State]: {
    name: "Slot 3 Cell 5 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell6State]: {
    name: "Slot 3 Cell 6 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell7State]: {
    name: "Slot 3 Cell 7 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell8State]: {
    name: "Slot 3 Cell 8 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell9State]: {
    name: "Slot 3 Cell 9 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell10State]: {
    name: "Slot 3 Cell 10 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell11State]: {
    name: "Slot 3 Cell 11 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell12State]: {
    name: "Slot 3 Cell 12 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell13State]: {
    name: "Slot 3 Cell 13 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell14State]: {
    name: "Slot 3 Cell 14 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell15State]: {
    name: "Slot 3 Cell 15 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot3_Slot3Cell16State]: {
    name: "Slot 3 Cell 16 State",
    category: Categories.RemixDeck_DirectMapping_Slot3,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },

  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING - SLOT 4 CELL TRIGGERS
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell1Trigger]: {
    name: "Slot 4 Cell 1 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell2Trigger]: {
    name: "Slot 4 Cell 2 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell3Trigger]: {
    name: "Slot 4 Cell 3 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell4Trigger]: {
    name: "Slot 4 Cell 4 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell5Trigger]: {
    name: "Slot 4 Cell 5 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell6Trigger]: {
    name: "Slot 4 Cell 6 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell7Trigger]: {
    name: "Slot 4 Cell 7 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell8Trigger]: {
    name: "Slot 4 Cell 8 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell9Trigger]: {
    name: "Slot 4 Cell 9 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell10Trigger]: {
    name: "Slot 4 Cell 10 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell11Trigger]: {
    name: "Slot 4 Cell 11 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell12Trigger]: {
    name: "Slot 4 Cell 12 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell13Trigger]: {
    name: "Slot 4 Cell 13 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell14Trigger]: {
    name: "Slot 4 Cell 14 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell15Trigger]: {
    name: "Slot 4 Cell 15 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell16Trigger]: {
    name: "Slot 4 Cell 16 Trigger",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING - SLOT 4 CELL STATES
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell1State]: {
    name: "Slot 4 Cell 1 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell2State]: {
    name: "Slot 4 Cell 2 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell3State]: {
    name: "Slot 4 Cell 3 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell4State]: {
    name: "Slot 4 Cell 4 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell5State]: {
    name: "Slot 4 Cell 5 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell6State]: {
    name: "Slot 4 Cell 6 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell7State]: {
    name: "Slot 4 Cell 7 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell8State]: {
    name: "Slot 4 Cell 8 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell9State]: {
    name: "Slot 4 Cell 9 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell10State]: {
    name: "Slot 4 Cell 10 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell11State]: {
    name: "Slot 4 Cell 11 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell12State]: {
    name: "Slot 4 Cell 12 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell13State]: {
    name: "Slot 4 Cell 13 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell14State]: {
    name: "Slot 4 Cell 14 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell15State]: {
    name: "Slot 4 Cell 15 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
  [KnownCommands.RemixDeck_DirectMapping_Slot4_Slot4Cell16State]: {
    name: "Slot 4 Cell 16 State",
    category: Categories.RemixDeck_DirectMapping_Slot4,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCellState",
  },
};
