/**
 * Command Metadata Part 2 - Track Deck, Remix Deck, and Mixer commands
 *
 * AIDEV-NOTE: This file continues the command metadata from command-metadata.ts.
 * It contains Track Deck, Remix Deck (including Direct Mapping), and Mixer commands.
 *
 * @see cmdr/cmdr.TsiLib/Commands/Interpretation/KnownCommands.cs
 */

import { Categories } from "./categories";
import type { CommandDescriptionInput } from "./command-description";
import { CommandInType, CommandOutType, FloatRangeType } from "./command-types";
import { KnownCommands } from "./known-commands";
import { TargetType } from "./target-type";

/**
 * Track Deck, Remix Deck, and Mixer command metadata.
 * This is merged with the main COMMAND_METADATA in command-metadata.ts.
 */
export const COMMAND_METADATA_PART2: Record<number, CommandDescriptionInput> = {
  // ===========================================================================
  // TRACK DECK - CUE
  // ===========================================================================
  [KnownCommands.TrackDeck_Cue_SetCueAndStoreAsNextHotcue]: {
    name: "Set Cue And Store As Next Hotcue",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Cue_StoreFloatingCueLoopAsNextHotcue]: {
    name: "Store Floating Cue/Loop As Next Hotcue",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Cue_DeleteCurrentHotcue]: {
    name: "Delete Current Hotcue",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Cue_JumpToNextPrevCueLoop]: {
    name: "Jump To Next/Prev Cue/Loop",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "JumpDirection",
  },
  [KnownCommands.TrackDeck_Cue_MapHotcue]: {
    name: "Map Hotcue",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.TrackDeck_Cue_SelectSetStoreHotcue]: {
    name: "Select/Set+Store Hotcue",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.HoldEnum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "Hotcue",
  },
  [KnownCommands.TrackDeck_Cue_DeleteHotcue]: {
    name: "Delete Hotcue",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "Hotcue",
  },
  [KnownCommands.TrackDeck_Cue_CueTypeSelector]: {
    name: "Cue Type Selector",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "CueType",
  },
  [KnownCommands.TrackDeck_Cue_JumpToActiveCuePointQuantized]: {
    name: "Jump to active Cue Point (quantized)",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  // Hotcue Type outputs (1-8)
  [KnownCommands.TrackDeck_Cue_Hotcue1Type]: {
    name: "Hotcue 1 Type",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "HotcueType",
  },
  [KnownCommands.TrackDeck_Cue_Hotcue2Type]: {
    name: "Hotcue 2 Type",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "HotcueType",
  },
  [KnownCommands.TrackDeck_Cue_Hotcue3Type]: {
    name: "Hotcue 3 Type",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "HotcueType",
  },
  [KnownCommands.TrackDeck_Cue_Hotcue4Type]: {
    name: "Hotcue 4 Type",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "HotcueType",
  },
  [KnownCommands.TrackDeck_Cue_Hotcue5Type]: {
    name: "Hotcue 5 Type",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "HotcueType",
  },
  [KnownCommands.TrackDeck_Cue_Hotcue6Type]: {
    name: "Hotcue 6 Type",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "HotcueType",
  },
  [KnownCommands.TrackDeck_Cue_Hotcue7Type]: {
    name: "Hotcue 7 Type",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "HotcueType",
  },
  [KnownCommands.TrackDeck_Cue_Hotcue8Type]: {
    name: "Hotcue 8 Type",
    category: Categories.TrackDeck_Cue,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "HotcueType",
  },

  // ===========================================================================
  // TRACK DECK - GRID
  // ===========================================================================
  [KnownCommands.TrackDeck_Grid_Autogrid]: {
    name: "Autogrid",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Grid_ResetBPM]: {
    name: "Reset BPM",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Grid_CopyPhaseFromTempoMaster]: {
    name: "Copy Phase From Tempo Master",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Grid_SetGridMarker]: {
    name: "Set Grid Marker",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Grid_DeleteGridMarker]: {
    name: "Delete Grid Marker",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Grid_MoveGridMarker]: {
    name: "Move Grid Marker",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.TrackDeck_Grid_BPMAdjust]: {
    name: "BPM Adjust",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.TrackDeck_Grid_BPMLockOn]: {
    name: "BPM Lock On",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.TrackDeck_Grid_BPMx2]: {
    name: "BPM x2",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Grid_BPMDiv2]: {
    name: "BPM /2",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Grid_BeatTap]: {
    name: "Beat Tap (Track Deck - Grid)",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_Grid_TickOn]: {
    name: "Tick On (Track Deck - Grid)",
    category: Categories.TrackDeck_Grid,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },

  // ===========================================================================
  // TRACK DECK - MAIN
  // ===========================================================================
  [KnownCommands.TrackDeck_Load]: {
    name: "Load Loop and Play (Track Deck)",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_DuplicateTrackDeckA]: {
    name: "Duplicate Track Deck A",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_DuplicateTrackDeckB]: {
    name: "Duplicate Track Deck B",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_DuplicateTrackDeckC]: {
    name: "Duplicate Track Deck C",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_DuplicateTrackDeckD]: {
    name: "Duplicate Track Deck D",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.TrackDeck_TrackEndWarning]: {
    name: "Track End Warning",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.TrackDeck_PotFadeOutMarker]: {
    name: "Post Fade-Out Marker (dug)",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.TrackDeck_WaveformZoomAdjust]: {
    name: "Waveform Zoom Adjust",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.TrackDeck_DawView]: {
    name: "DAW View",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.TrackDeck_KeylockOn]: {
    name: "Keylock On",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.TrackDeck_KeylockOnPreservePitch]: {
    name: "Keylock On (Preserve Pitch)",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.TrackDeck_KeyAdjust]: {
    name: "Key Adjust",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.TrackDeck_SemiToneUpDown]: {
    name: "Semitone Up/Down",
    category: Categories.TrackDeck,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "JumpDirection",
  },

  // ===========================================================================
  // REMIX DECK - LEGACY
  // ===========================================================================
  [KnownCommands.RemixDeck_Legacy_PlayAllSlots]: {
    name: "Play All Slots",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_Legacy_TriggerAllSlots]: {
    name: "Trigger All Slots",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_Legacy_SlotRetriggerPlay]: {
    name: "Slot Retrigger Play",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_Legacy_SlotLoadFromList]: {
    name: "Slot Load From List",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_Legacy_SlotUnload]: {
    name: "Slot Unload",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_Legacy_SlotCaptureFromDeck]: {
    name: "Slot Capture From Deck",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "Deck",
  },
  [KnownCommands.RemixDeck_Legacy_SlotCaptureFromLoopRecorder]: {
    name: "Slot Capture From Loop Recorder",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_Legacy_SlotCopyFromSlot]: {
    name: "Slot Copy From Slot",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotCell",
  },
  [KnownCommands.RemixDeck_Legacy_PlayModeAllSlots]: {
    name: "Play Mode All Slots",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "PlayMode",
  },
  [KnownCommands.RemixDeck_Legacy_SlotSizex2]: {
    name: "Slot Size x2",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_Legacy_SlotSizeDiv2]: {
    name: "Slot Size /2",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_Legacy_SlotSizeReset]: {
    name: "Slot Size Reset",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_Legacy_SlotSizeAdjust]: {
    name: "Slot Size Adjust",
    category: Categories.RemixDeck_Legacy,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotSize",
  },

  // ===========================================================================
  // REMIX DECK - DIRECT MAPPING MODIFIERS
  // ===========================================================================
  [KnownCommands.RemixDeck_DirectMapping_CellLoadModifier]: {
    name: "Cell Load Modifier",
    category: Categories.RemixDeck_DirectMapping,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_CellDeleteModifier]: {
    name: "Cell Delete Modifier",
    category: Categories.RemixDeck_DirectMapping,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_CellReverseModifier]: {
    name: "Cell Reverse Modifier",
    category: Categories.RemixDeck_DirectMapping,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_DirectMapping_CellCaptureModifier]: {
    name: "Cell Capture Modifier",
    category: Categories.RemixDeck_DirectMapping,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Hold,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // REMIX DECK - STEP SEQUENCER
  // ===========================================================================
  [KnownCommands.RemixDeck_StepSequencer_SequencerOn]: {
    name: "Sequencer On",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_SwingAmount]: {
    name: "Swing Amount",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.SwingAmount,
  },
  [KnownCommands.RemixDeck_StepSequencer_CurrentStep]: {
    name: "Current Step",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "Sample",
  },
  [KnownCommands.RemixDeck_StepSequencer_SelectedSample]: {
    name: "Selected Sample",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "Sample",
  },
  [KnownCommands.RemixDeck_StepSequencer_PatternLength]: {
    name: "Pattern Length",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "PatternLength",
  },
  // Step Sequencer Enable Steps (1-16)
  [KnownCommands.RemixDeck_StepSequencer_EnableStep1]: {
    name: "Enable Step 1",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep2]: {
    name: "Enable Step 2",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep3]: {
    name: "Enable Step 3",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep4]: {
    name: "Enable Step 4",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep5]: {
    name: "Enable Step 5",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep6]: {
    name: "Enable Step 6",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep7]: {
    name: "Enable Step 7",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep8]: {
    name: "Enable Step 8",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep9]: {
    name: "Enable Step 9",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep10]: {
    name: "Enable Step 10",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep11]: {
    name: "Enable Step 11",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep12]: {
    name: "Enable Step 12",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep13]: {
    name: "Enable Step 13",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep14]: {
    name: "Enable Step 14",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep15]: {
    name: "Enable Step 15",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_StepSequencer_EnableStep16]: {
    name: "Enable Step 16",
    category: Categories.RemixDeck_StepSequencer,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },

  // ===========================================================================
  // REMIX DECK - MAIN
  // ===========================================================================
  [KnownCommands.RemixDeck_SaveRemixSet]: {
    name: "Save Remix Set",
    category: Categories.RemixDeck,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_LoadSetFromList]: {
    name: "Load Set From List",
    category: Categories.RemixDeck,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_SlotCaptureTriggerMute]: {
    name: "Slot Capture/Trigger/Mute",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_SlotStopDeleteLoadFromList]: {
    name: "Slot Stop/Delete/Load From List",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.RemixDeck_SlotRetrigger]: {
    name: "Slot Retrigger",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_SlotPlayMode]: {
    name: "Slot Play Mode",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "PlayMode",
  },
  [KnownCommands.RemixDeck_SlotTriggerType]: {
    name: "Slot Trigger Type",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotTriggerType",
  },
  [KnownCommands.RemixDeck_SlotKeylockOn]: {
    name: "Slot Keylock On",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_SlotState]: {
    name: "Slot State",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SlotState",
  },
  [KnownCommands.RemixDeck_SlotMonitorOn]: {
    name: "Slot Monitor On",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_SlotPunchOn]: {
    name: "Slot Punch On",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_QuantizeSelector]: {
    name: "Quantize Selector",
    category: Categories.RemixDeck,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "QuantizeSize",
  },
  [KnownCommands.RemixDeck_QuantizeOn]: {
    name: "Quantize On (Remix Deck)",
    category: Categories.RemixDeck,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.RemixDeck_CaptureSourceSelector]: {
    name: "Capture Source Selector",
    category: Categories.RemixDeck,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "CaptureSource",
  },
  [KnownCommands.RemixDeck_SamplePageSelector]: {
    name: "Sample Page Selector",
    category: Categories.RemixDeck,
    targetType: TargetType.Remix,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "SamplePage",
  },
  [KnownCommands.RemixDeck_DeckPlay]: {
    name: "Deck Play (Remix Deck) (dug)",
    category: Categories.RemixDeck,
    targetType: TargetType.Slot,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },

  // ===========================================================================
  // MIXER - EQ
  // ===========================================================================
  [KnownCommands.Mixer_EQ_HighAdjust]: {
    name: "High Adjust",
    category: Categories.Mixer_EQ,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_EQ_HighKill]: {
    name: "High Kill",
    category: Categories.Mixer_EQ,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_EQ_MidAdjust]: {
    name: "Mid Adjust",
    category: Categories.Mixer_EQ,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_EQ_MidKill]: {
    name: "Mid Kill",
    category: Categories.Mixer_EQ,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_EQ_MidLowAdjust]: {
    name: "Mid Low Adjust",
    category: Categories.Mixer_EQ,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_EQ_MidLowKill]: {
    name: "Mid Low Kill",
    category: Categories.Mixer_EQ,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_EQ_LowAdjust]: {
    name: "Low Adjust",
    category: Categories.Mixer_EQ,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_EQ_LowKill]: {
    name: "Low Kill",
    category: Categories.Mixer_EQ,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },

  // ===========================================================================
  // MIXER - X-FADER
  // ===========================================================================
  [KnownCommands.Mixer_XFader_PositionXFader]: {
    name: "Position (X-Fader)",
    category: Categories.Mixer_XFader,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_XFader_CurveAdjust]: {
    name: "Curve Adjust",
    category: Categories.Mixer_XFader,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_XFader_AssignLeft]: {
    name: "Assign Left",
    category: Categories.Mixer_XFader,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_XFader_AssignRight]: {
    name: "Assign Right",
    category: Categories.Mixer_XFader,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_XFader_AutoXFadeLeft]: {
    name: "Auto X-Fade Left",
    category: Categories.Mixer_XFader,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Mixer_XFader_AutoXFadeRight]: {
    name: "Auto X-Fade Right",
    category: Categories.Mixer_XFader,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
};
