/**
 * Command Metadata Part 3 - Mixer, FX Unit, Browser, Global commands
 *
 * AIDEV-NOTE: This file continues the command metadata.
 * It contains Mixer (main, meters), FX Unit, Browser, Global, Layout,
 * Modifier, Master Clock, Loop Recorder, Audio Recorder, and Preview Player commands.
 *
 * @see cmdr/cmdr.TsiLib/Commands/Interpretation/KnownCommands.cs
 */

import { Categories } from "./categories";
import type { CommandDescriptionInput } from "./command-description";
import { CommandInType, CommandOutType, FloatRangeType } from "./command-types";
import { KnownCommands } from "./known-commands";
import { TargetType } from "./target-type";

/**
 * Mixer, FX Unit, Browser, Global, and other command metadata.
 */
export const COMMAND_METADATA_PART3: Record<number, CommandDescriptionInput> = {
  // ===========================================================================
  // MIXER - METERS
  // ===========================================================================
  [KnownCommands.Mixer_Meters_DeckPostFaderLevelL]: {
    name: "Deck Post-Fader Level (L)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_DeckPostFaderLevelR]: {
    name: "Deck Post-Fader Level (R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_DeckPostFaderLevelLR]: {
    name: "Deck Post-Fader Level (L+R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_DeckPreFaderLevelL]: {
    name: "Deck Pre-Fader Level (L)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_DeckPreFaderLevelR]: {
    name: "Deck Pre-Fader Level (R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_DeckPreFaderLevelLR]: {
    name: "Deck Pre-Fader Level (L+R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Track,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_MixerLevelL]: {
    name: "Mixer Level (L)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_MixerLevelR]: {
    name: "Mixer Level (R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_MasterOutLevelL]: {
    name: "Master Out Level (L)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_MasterOutLevelR]: {
    name: "Master Out Level (R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_MasterOutLevelLR]: {
    name: "Master Out Level (L+R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_MasterOutClipL]: {
    name: "Master Out Clip (L)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_MasterOutClipR]: {
    name: "Master Out Clip (R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_MasterOutClipLR]: {
    name: "Master Out Clip (L+R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_RecordInputLevelL]: {
    name: "Record Input Level (L)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_RecordInputLevelR]: {
    name: "Record Input Level (R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_RecordInputClipL]: {
    name: "Record Input Clip (L)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_Meters_RecordInputClipR]: {
    name: "Record Input Clip (R)",
    category: Categories.Mixer_Meters,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },

  // ===========================================================================
  // MIXER - MAIN
  // ===========================================================================
  [KnownCommands.Mixer_GainAdjust]: {
    name: "Gain Adjust (Mixer)",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_AutoGainAdjust]: {
    name: "Auto-Gain Adjust",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_AutoGainViewOn]: {
    name: "Auto-Gain View On",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_FXUnit1On]: {
    name: "FX Unit 1 On",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_FXUnit2On]: {
    name: "FX Unit 2 On",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_FXUnit3On]: {
    name: "FX Unit 3 On",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_FXUnit4On]: {
    name: "FX Unit 4 On",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_DeckEffectOn]: {
    name: "Deck Effect On",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_FilterAdjust]: {
    name: "Mixer FX Adjust",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_FilterOn]: {
    name: "Mixer FX On",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_MixerFXSelector]: {
    name: "Mixer FX Selector",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "MixerFx",
  },
  [KnownCommands.Mixer_BalanceAdjust]: {
    name: "Balance Adjust",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_MonitorCueOn]: {
    name: "Monitor Cue On",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_VolumeAdjust]: {
    name: "Volume Adjust",
    category: Categories.Mixer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_MasterVolumeAdjust]: {
    name: "Master Volume Adjust",
    category: Categories.Mixer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_LimiterOn]: {
    name: "Limiter On",
    category: Categories.Mixer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Mixer_MonitorVolumeAdjust]: {
    name: "Monitor Volume Adjust",
    category: Categories.Mixer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.Mixer_MonitorMixAdjust]: {
    name: "Monitor Mix Adjust",
    category: Categories.Mixer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },
  [KnownCommands.Mixer_MicrophoneGainAdjust]: {
    name: "Microphone Gain Adjust",
    category: Categories.Mixer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Centered,
  },

  // ===========================================================================
  // FX UNIT
  // ===========================================================================
  [KnownCommands.FXUnit_UnitOn]: {
    name: "Unit On (FX Unit)",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.FXUnit_DryWetAdjust]: {
    name: "Dry/Wet Adjust (FX Unit)",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.FXUnit_Knob1]: {
    name: "Knob 1",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.FXUnit_Knob2]: {
    name: "Knob 2",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.FXUnit_Knob3]: {
    name: "Knob 3",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.FXUnit_Button1]: {
    name: "Button 1",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.FXUnit_Button2]: {
    name: "Button 2",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.FXUnit_Button3]: {
    name: "Button 3",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.FXUnit_Effect1Selector]: {
    name: "Effect 1 Selector",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.EffectSelector,
    outCommandType: CommandOutType.EffectSelector,
  },
  [KnownCommands.FXUnit_Effect2Selector]: {
    name: "Effect 2 Selector",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.EffectSelector,
    outCommandType: CommandOutType.EffectSelector,
  },
  [KnownCommands.FXUnit_Effect3Selector]: {
    name: "Effect 3 Selector",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.EffectSelector,
    outCommandType: CommandOutType.EffectSelector,
  },
  [KnownCommands.FXUnit_FXUnitModeSelector]: {
    name: "FX Unit Mode Selector",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "FXUnitMode",
  },
  [KnownCommands.FXUnit_RoutingSelector]: {
    name: "Routing Selector",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "FXRouting",
  },
  [KnownCommands.FXUnit_FXStorePreset]: {
    name: "FX Store Preset",
    category: Categories.FXUnit,
    targetType: TargetType.FX,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.FXUnit_EffectLFOReset]: {
    name: "Effect LFO Reset",
    category: Categories.FXUnit,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // LOOP RECORDER
  // ===========================================================================
  [KnownCommands.LoopRecorder_Record]: {
    name: "Record (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.LoopRecorder_Size]: {
    name: "Size (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "LoopRecorderSize",
  },
  [KnownCommands.LoopRecorder_DryWetAdjust]: {
    name: "Dry/Wet Adjust (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.LoopRecorder_PlayPause]: {
    name: "Play/Pause (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.LoopRecorder_Delete]: {
    name: "Delete (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.LoopRecorder_UndoRedo]: {
    name: "Undo/Redo (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.LoopRecorder_PlaybackPosition]: {
    name: "Playback Position (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.LoopRecorder_UndoState]: {
    name: "Undo State (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "LoopRecorderUndoState",
  },
  [KnownCommands.LoopRecorder_State]: {
    name: "State (Loop Recorder)",
    category: Categories.LoopRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.None,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "LoopRecorderState",
  },

  // ===========================================================================
  // AUDIO RECORDER
  // ===========================================================================
  [KnownCommands.AudioRecorder_RecordStop]: {
    name: "Record/Stop (Audio Recorder)",
    category: Categories.AudioRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.AudioRecorder_Cut]: {
    name: "Cut (Audio Recorder)",
    category: Categories.AudioRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.AudioRecorder_GainAdjust]: {
    name: "Gain Adjust (Audio Recorder)",
    category: Categories.AudioRecorder,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.AudioRecorder_LoadLastRecording]: {
    name: "Load Last Recording (Audio Recorder)",
    category: Categories.AudioRecorder,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // MASTER CLOCK
  // ===========================================================================
  [KnownCommands.MasterClock_AbletonLink_ResetDownbeat]: {
    name: "Reset Downbeat",
    category: Categories.MasterClock_AbletonLink,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.MasterClock_AutoMasterMode]: {
    name: "Auto Master Mode",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.MasterClock_MasterTempoSelector]: {
    name: "Master Tempo Selector",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "TempoSource",
  },
  [KnownCommands.MasterClock_SetMasterTempo]: {
    name: "Set Master Tempo",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.MasterTempo,
  },
  [KnownCommands.MasterClock_TempoBendUp]: {
    name: "Tempo Bend Up",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.MasterClock_TempoBendDown]: {
    name: "Tempo Bend Down",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.MasterClock_BeatTap]: {
    name: "Beat Tap (Master Clock)",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.MasterClock_TickOn]: {
    name: "Tick On (Master Clock)",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.MasterClock_ClockIntExt]: {
    name: "Clock Int/Ext",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "IntExt",
  },
  [KnownCommands.MasterClock_ClockSend]: {
    name: "Clock Send",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.MasterClock_ClockTriggerMIDISync]: {
    name: "Clock Trigger MIDI Sync",
    category: Categories.MasterClock,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // PREVIEW PLAYER
  // ===========================================================================
  [KnownCommands.PreviewPlayer_LoadPreviewPlayerIntoDeck]: {
    name: "Load Preview Player into Deck",
    category: Categories.PreviewPlayer,
    targetType: TargetType.Track,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.PreviewPlayer_LoadSelected]: {
    name: "Load Selected (Preview Player)",
    category: Categories.PreviewPlayer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.PreviewPlayer_PlayPause]: {
    name: "Play/Pause (Preview Player)",
    category: Categories.PreviewPlayer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.PreviewPlayer_SeekPosition]: {
    name: "Seek Position (Preview Player)",
    category: Categories.PreviewPlayer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Float,
    outCommandType: CommandOutType.Float,
    floatRangeType: FloatRangeType.Relative,
  },
  [KnownCommands.PreviewPlayer_Unload]: {
    name: "Unload (Preview Player)",
    category: Categories.PreviewPlayer,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // GLOBAL
  // ===========================================================================
  [KnownCommands.Global_SnapOn]: {
    name: "Snap On",
    category: Categories.Global,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_QuantizeOn]: {
    name: "Quant On (Global)",
    category: Categories.Global,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_BroadcastingOn]: {
    name: "Broadcasting On",
    category: Categories.Global,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_CruiseModeOn]: {
    name: "Cruise Mode On",
    category: Categories.Global,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_ShowSliderValuesOn]: {
    name: "Show Slider Values On",
    category: Categories.Global,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_ToolTipsOn]: {
    name: "Tool Tips On",
    category: Categories.Global,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Global_SendMonitorState]: {
    name: "Send Monitor State",
    category: Categories.Global,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },
  [KnownCommands.Global_SaveTraktorSettings]: {
    name: "Save Traktor Settings",
    category: Categories.Global,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // LAYOUT
  // ===========================================================================
  [KnownCommands.Layout_OnlyBrowserOn]: {
    name: "Only Browser On",
    category: Categories.Layout,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Layout_LayoutSelector]: {
    name: "Layout Selector",
    category: Categories.Layout,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "Layout",
  },
  [KnownCommands.Layout_FullscreenOn]: {
    name: "Fullscreen On",
    category: Categories.Layout,
    targetType: TargetType.Global,
    inCommandType: CommandInType.OnOff,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "OnOff",
  },
  [KnownCommands.Layout_DeckFocusSelector]: {
    name: "Deck Focus Selector",
    category: Categories.Layout,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "Deck",
  },
  [KnownCommands.Layout_ToggleLastFocus]: {
    name: "Toggle Last Focus",
    category: Categories.Layout,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Trigger,
    outCommandType: CommandOutType.Trigger,
  },

  // ===========================================================================
  // MODIFIER
  // ===========================================================================
  [KnownCommands.Modifier_Modifier1]: {
    name: "Modifier #1",
    category: Categories.Modifier,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ModifierValue",
  },
  [KnownCommands.Modifier_Modifier2]: {
    name: "Modifier #2",
    category: Categories.Modifier,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ModifierValue",
  },
  [KnownCommands.Modifier_Modifier3]: {
    name: "Modifier #3",
    category: Categories.Modifier,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ModifierValue",
  },
  [KnownCommands.Modifier_Modifier4]: {
    name: "Modifier #4",
    category: Categories.Modifier,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ModifierValue",
  },
  [KnownCommands.Modifier_Modifier5]: {
    name: "Modifier #5",
    category: Categories.Modifier,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ModifierValue",
  },
  [KnownCommands.Modifier_Modifier6]: {
    name: "Modifier #6",
    category: Categories.Modifier,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ModifierValue",
  },
  [KnownCommands.Modifier_Modifier7]: {
    name: "Modifier #7",
    category: Categories.Modifier,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ModifierValue",
  },
  [KnownCommands.Modifier_Modifier8]: {
    name: "Modifier #8",
    category: Categories.Modifier,
    targetType: TargetType.Global,
    inCommandType: CommandInType.Enum,
    outCommandType: CommandOutType.Enum,
    valueEnumType: "ModifierValue",
  },
};
